[package]
name = "titan"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rustls]
version = "0.18.1"
features = ["dangerous_configuration"]

[dependencies.webpki]
version = "0.21.3"
